- name: Create sample index.html
  shell: echo "<h1>This is NGINX Web Server from {{ inventory_hostname }}</h1>" | sudo tee /var/www/html/index.html

- name: Copy check script
  template:
    src: check_nginx.sh.j2
    dest: /bin/check_nginx.sh

- name: Set permission on check script.
  file: path=/bin/check_nginx.sh mode=755

- name: Copy config keepalived.
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf

- name: Restart nginx and keepalived
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - nginx
    - keepalived
